src/Entity/Book.php
<?php
namespace App\Entity;

use App\Repository\BookRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BookRepository::class)]
class Book
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\ManyToOne(inversedBy: 'books')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $category = null;

    #[ORM\Column]
    private ?int $pages = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $publication_date = null;

    #[ORM\Column]
    private ?\DateTime $created_at = null;

    #[ORM\Column]
    private ?\DateTime $updated_at = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }

    public function getPages(): ?int
    {
        return $this->pages;
    }

    public function setPages(int $pages): static
    {
        $this->pages = $pages;

        return $this;
    }

    public function getPublicationDate(): ?\DateTimeInterface
    {
        return $this->publication_date;
    }

    public function setPublicationDate(\DateTimeInterface $publication_date): static
    {
        $this->publication_date = $publication_date;

        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTime $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTime
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTime $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

src/Controller/HomeController.php
<?php
namespace App\Controller;

use App\Service\BookService;
use App\Service\AuthService;
use App\Form\AddBookType;
use App\Form\LoginFormType;
use App\Form\RegisterFormType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    private BookService $bookService;
    private AuthService $authService;

    public function __construct(
        BookService $bookService,
        AuthService $authService
    ) {
        $this->bookService = $bookService;
        $this->authService = $authService;
    }

    #[Route('/', name: 'app.home')]
    public function index(Request $request): Response
    {
        $userId = 1;

        $addBookForm = $this->createForm(AddBookType::class);
        $addBookForm->handleRequest($request);
        if ($addBookForm->isSubmitted() && $addBookForm->isValid()) {
            $data = $addBookForm->getData();
            $this->bookService->addBookRead($userId, $data);
        }

        return $this->render('pages/home.html.twig', [
            'name' => 'Accueil',
            'booksReading' => $this->bookService->getBooksReading($userId),
            'booksRead' => $this->bookService->getBooksRead($userId),
            'addBookForm' => $addBookForm->createView()
        ]);
    }

    #[Route('/login', name: 'auth.login')]
    public function login(Request $request): Response
    {
        $loginForm = $this->createForm(LoginFormType::class);
        $loginForm->handleRequest($request);

        if ($loginForm->isSubmitted() && $loginForm->isValid()) {
            $data = $loginForm->getData();
            if ($this->authService->authenticateUser($data)) {
                return $this->redirectToRoute('app.home');
            }
        }

        return $this->render('auth/login.html.twig', [
            'name' => 'Connexion',
            'form' => $loginForm->createView(),
        ]);
    }

    #[Route('/register', name: 'auth.register')]
    public function register(Request $request): Response
    {
        $registerForm = $this->createForm(RegisterFormType::class);
        $registerForm->handleRequest($request);

        if ($registerForm->isSubmitted() && $registerForm->isValid()) {
            $data = $registerForm->getData();
            if ($this->authService->registerUser($data)) {
                return $this->redirectToRoute('auth.login');
            }
        }

        return $this->render('auth/register.html.twig', [
            'name' => 'Inscription',
            'form' => $registerForm->createView(),
        ]);
    }
}

templates/components/home/booksRead.html.twig
<div class="card card-grid h-full min-w-full">
    <div class="card-header">
        <h3 class="card-title">
            Mes lectures terminées
        </h3>
        <div class="input input-sm max-w-48">
            <i class="ki-filled ki-magnifier">
            </i>
            <input data-datatable-search="#read-books-table" placeholder="Rechercher" type="text"/>
        </div>
    </div>
    <div class="card-body">
        <div id="read-books-table" data-datatable="true" data-datatable-page-size="5">
            <div class="scrollable-x-auto">
                <table class="table table-border" data-datatable-table="true">
                    <thead>
                    <tr>
                        <th class="min-w-[280px]">
                            <span class="sort asc">
                                <span class="sort-label">Livre</span>
                                <span class="sort-icon"></span>
                            </span>
                        </th>
                        <th class="min-w-[135px]">
                            <span class="sort asc">
                                <span class="sort-label">Catégorie</span>
                                <span class="sort-icon"></span>
                            </span>
                        </th>
                        <th class="min-w-[135px]">
                            <span class="sort asc">
                                <span class="sort-label">Note</span>
                                <span class="sort-icon"></span>
                            </span>
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for bookRead in booksRead %}
                    <tr>
                        <td>
                            <div class="flex flex-col gap-2">
                                <a class="leading-none font-medium text-sm text-gray-900 hover:text-primary"
                                   href="#">
                                    {{ bookRead.name }}
                                </a>
                                <span class="text-2sm text-gray-700 font-normal leading-3">
                                    {{ bookRead.description }}
                                </span>
                            </div>
                        </td>
                        <td>{{ bookRead.category }}</td>
                        <td>
                            {% for i in 0..bookRead.rating-1 %}
                            <div class="rating">
                                <div class="rating-label checked">
                                    <i class="rating-on ki-solid ki-star text-base leading-none"></i>
                                    <i class="rating-off ki-outline ki-star text-base leading-none"></i>
                                </div>
                            </div>
                            {% endfor %}
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="card-footer justify-center md:justify-between flex-col md:flex-row gap-5 text-gray-600 text-2sm font-medium">
                <div class="flex items-center gap-2 order-2 md:order-1">
                    Show
                    <select class="select select-sm w-16"
                            data-datatable-size="true" name="perpage">
                    </select>
                    per page
                </div>
                <div class="flex items-center gap-4 order-1 md:order-2">
                    <span data-datatable-info="true"></span>
                    <div class="pagination" data-datatable-pagination="true">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/components/home/booksReading.html.twig
<div class="card card-grid h-full min-w-full">
    <div class="card-header">
        <h3 class="card-title">
            Mes lectures en cours
        </h3>
        <div class="input input-sm max-w-48">
            <i class="ki-filled ki-magnifier">
            </i>
            <input data-datatable-search="#current-books-table" placeholder="Rechercher" type="text"/>
        </div>
    </div>
    <div class="card-body">
        <div id="current-books-table" data-datatable="true" data-datatable-page-size="5">
            <div class="scrollable-x-auto">
                <table  class="table table-border" data-datatable-table="true">
                    <thead>
                    <tr>
                        <th class="min-w-[280px]">
                            <span class="sort asc">
                                <span class="sort-label">Livre</span>
                                <span class="sort-icon"></span>
                            </span>
                        </th>
                        <th class="max-w-[135px] text-end">
                            <span class="sort">
                                <span class="sort-label">Modifié le</span>
                                <span class="sort-icon"></span>
                            </span>
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for bookReading in booksReading %}
                        <tr>
                            <td>
                                <div class="flex flex-col gap-2">
                                    <a class="leading-none font-medium text-sm text-gray-900 hover:text-primary"
                                       href="#">
                                        {{ bookReading.name }}
                                    </a>
                                    <span class="text-2sm text-gray-700 font-normal leading-3">
                                        {{ bookReading.description }}
                                </span>
                                </div>
                            </td>
                            <td class="text-end">
                                {{ bookReading.updatedAt|date('d/m/Y à H:i') }}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="card-footer justify-center md:justify-between flex-col md:flex-row gap-5 text-gray-600 text-2sm font-medium">
                <div class="flex items-center gap-4 order-1 md:order-2">
                    <span data-datatable-info="true"></span>
                    <div class="pagination" data-datatable-pagination="true"></div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/components/home/radarChart.html.twig
<div class="card h-full">
    <div class="card-header">
        <h3 class="card-title">
            Répartition de mes lectures
        </h3>
    </div>
    <div id="radar" class="card-body min-h-full max-h-full min-w-full max-w-full w-full h-full flex flex-col gap-5">
    </div>
</div>